### ISSUE TITLE
Blank Streams Screen / L.next is not a function

### ISSUE THREAD

**Issue by tachyon65** [streamlink/streamlink-twitch-gui#517]
----

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I have read the contribution guidelines und used the search function to find already existing threads.

### Description
When searching for or directly viewing a game, sometimes the resulting screen is blank. It's fairly inconsistent though.

### Expected / Actual behavior

It should display properly.

### Reproduction steps

1. Search for battlerite, haven't really tested it with other games.

### Environment details

Operating system and version: Arch Linux
Streamlink Twitch GUI version: streamlink-twitch-gui 1.4.1, from AUR
Streamlink version: 0.9.0-1

### Comments, logs, screenshots, etc.
The only thing in the log is "TypeError: L.next is not a function".
I think it started showing up after the upgrade from 1.3.1.

Blank
![ss-2017-12-10_02 10 16](https://user-images.githubusercontent.com/34412197/33802993-32f7dce8-dd53-11e7-92ab-0973fcf2a736.png)
Correct
![ss-2017-12-10_02 11 22](https://user-images.githubusercontent.com/34412197/33802994-330a687c-dd53-11e7-8cfd-de67e2ed7013.png)

**Comment by bastimeyer** [comment]
Thanks for the report!
That's caused by a bug related to stream languages when a streamer has selected "other" as broadcasting language. I'll fix this later today.

**Comment by bastimeyer** [comment]
Fixed by 83cadfc...
Since you're on Arch, you can use the `streamlink-twitch-gui-git` AUR package if you want to be able to run the latest version. Or just build it manually.
Thanks again!
